### ISSUE TITLE
How to disable audio module

### ISSUE THREAD

**Issue by realdog** [emotionLoop/visualCaptcha-node#9]
I want disable audio module,  but i couldn't found  how setup it....

**Comment by BrunoBernardino** [comment]
If the browser doesn't support it, it'll be disabled automatically.

However, for manual disabling, in the front-end code, simply remove the audio-related portion. Look into `supportsAudio` method.

Let me know if you need further help.

**Comment by realdog** [comment]
Thank you for your reply.
When i changed supportsAudio function(return false from supportsAudio)
```
      return false;
      var e, t = !1;
      try {
        e = document.createElement("audio"), e.canPlayType && (t = !0)
      } catch (n) {}
      return t;
```

In the front-end interface,some buttons can't be select (reload, cat, tree, clould..etc...)

**Comment by realdog** [comment]
I found ,i must change  other part 。。。。。
Because the js code has been condensed， so i can't pointed out the specific location....
```
else e.addEventListener ? e.addEventListener("click", t, !1) : e.attachEvent("onclick", t)
```

change to 

```
else if(!!e) e.addEventListener ? e.addEventListener("click", t, !1) : e.attachEvent("onclick", t)
```

**Comment by realdog** [comment]
Can u get not compression version of new Front-end js file?

**Comment by realdog** [comment]
Can we get the new  version of not compression  js file( for Front-end)?

**Comment by BrunoBernardino** [comment]
Uncompressed is at https://github.com/emotionLoop/visualCaptcha-frontend-core/tree/master/src

**Comment by realdog** [comment]
Thank u very much!
